<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <Product>Windows Vertical Dock</Product>
    <Company>dock-Manager</Company>
    <Copyright>Copyright (c) Ram</Copyright>
    <Version>0.1.1</Version>
    <AssemblyVersion>0.1.1.0</AssemblyVersion>
    <FileVersion>0.1.1.0</FileVersion>
    <InformationalVersion>0.1.1</InformationalVersion>
  </PropertyGroup>

</Project>
